### ISSUE TITLE
Milestone 3 Task Distribution

### ISSUE THREAD

**Issue by mmyz88** [UBC-MDS/DSCI532_Group17-R#2]
Yuanzhe Marco Ma:
- [ ] Address TA/instructor feedbacks
    - feedback actions summary: https://github.com/UBC-MDS/DSCI532_Group17/issues/20 
- [ ] Add more colours, add range-selection widgets and other potential improvements

Guanshu Tao: 
- [x] Translate overall layout to R
- [x] Write reflection

Sicheng Sun:
- [ ] Improve current plot with some interaction/colouring
- [x] Translate plots to ggplot

Yuan Xiong:
- [x] Translate callback/update functions to R
- [x] Write peer review feedbacks
